"""仓储接口协议 — 所有业务服务面向此协议编程."""
from typing import Protocol


class UserRepository(Protocol):
    def find_by_username(self, username: str) -> dict | None: ...
    def find_by_email(self, email: str) -> dict | None: ...
    def find_by_id(self, user_id: str) -> dict | None: ...
    def list_all(self) -> list[dict]: ...
    def create(self, user: dict) -> dict: ...
    def update(self, user_id: str, updates: dict) -> dict | None: ...
    def list_by_role(self, role: str) -> list[dict]: ...


class ContractRepository(Protocol):
    def find_by_id(self, contract_id: str) -> dict | None: ...
    def list_by_handler(self, handler_id: str, status: str | None = None) -> list[dict]: ...
    def list_all(self, status: str | None = None) -> list[dict]: ...
    def list_for_approver(self, approver_id: str) -> list[dict]: ...
    def create(self, contract: dict) -> dict: ...
    def update(self, contract_id: str, updates: dict) -> dict | None: ...
    def search(self, keyword: str, user_id: str | None = None, role: str | None = None) -> list[dict]: ...


class ApprovalRepository(Protocol):
    def find_by_contract(self, contract_id: str) -> list[dict]: ...
    def create(self, record: dict) -> dict: ...
    def update(self, record_id: str, updates: dict) -> dict | None: ...
    def find_pending_by_approver(self, approver_id: str) -> list[dict]: ...


class MessageRepository(Protocol):
    def list_by_user(self, user_id: str, is_read: bool | None = None) -> list[dict]: ...
    def create(self, message: dict) -> dict: ...
    def mark_read(self, message_id: str) -> dict | None: ...
    def unread_count(self, user_id: str) -> int: ...


class TemplateRepository(Protocol):
    def list_active(self) -> list[dict]: ...
    def list_all(self) -> list[dict]: ...
    def find_by_id(self, template_id: str) -> dict | None: ...
    def create(self, template: dict) -> dict: ...
    def update(self, template_id: str, updates: dict) -> dict | None: ...


class AuditRepository(Protocol):
    def create(self, log: dict) -> dict: ...
    def list_by_target(self, target_type: str, target_id: str) -> list[dict]: ...
